name: covi
description: A new Flutter project.
version: 1.5.6+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_splashscreen: ^0.1.3
  cupertino_icons: ^0.1.2
  fl_chart: ^0.9.2
  flip_card: ^0.4.4
  keyboard_visibility: ^0.5.6
  keyboard_actions: ^3.2.1
  http: ^0.12.0+4
  file_picker: ^1.5.1
  flutter_svg: ^0.17.4
  flutter_local_notifications: ^1.4.0
  share: ^0.6.3+6
  device_info: ^0.4.2+1
  permission_handler: ^4.4.0+hotfix.4
  google_maps_flutter: ^0.5.25+3
  connectivity: ^0.4.8+2
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.2
  provider: ^4.0.4
  shared_preferences: ^0.5.6+3
  geolocator: ^5.3.1
  route_observer_mixin: ^1.1.0
  encrypt: ^4.0.0
  localstorage: ^3.0.1+4
  path_provider: ^1.6.5
  logger: ^0.7.0
  intl: ^0.16.0
  logger_flutter: ^0.7.1
  flutter_launcher_icons: ^0.7.3
  uuid: ^2.0.4
  flutter_sodium: ^0.0.11
  pointycastle: ^1.0.2
  flutter_secure_storage: ^3.3.2
  background_fetch: ^0.5.5
  pascaldart: ^0.1.6
  flutter_i18n: ^0.13.0
  firebase_messaging: ^6.0.13
  infinity_page_view: ^1.0.0
  flutter_html: ^0.11.1
  enum_to_string: ^1.0.9
  geojson: ^0.9.1
  geopoint: ^0.7.1
  geodesy: ^0.3.2
  package_info: ^0.4.0+17
  version: ^1.0.0
  jiffy: ^3.0.1
  launch_review: ^2.0.0
  lzma: ^0.4.0+2
  flutter_phoenix: "^0.1.0"
  lottie: ^0.3.6
  devicelocale: ^0.2.3
  flutter_cache_manager: ^1.4.0
  flutter_rounded_date_picker:
    git:
      url: https://github.com/libeo/flutter_rounded_date_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate_gen: ^1.2.3
  build_runner: ^1.7.0

flutter:
  uses-material-design: true

  fonts:
    - family: Neue
      fonts:
        - asset: assets/fonts/NeueMontreal-Regular.otf
          weight: 400
        - asset: assets/fonts/NeueMontreal-Bold.otf
          weight: 700
        - asset: assets/fonts/NeueMontreal-Medium.otf
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  assets:
    - assets/i18n/
    - assets/img/
    - assets/svg/
    - assets/svg/backdrops/
    - assets/svg/navbar/
    - assets/data/
    - assets/animations/

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"
